# Regenerates sprites.js: where the Pokémon sits inside each Gen 2-4 shiny sprite on Showdown,
# so the page can trim the empty space around it. Needs Pillow. Run: python3 sprite_crops.py
import io, json, re, urllib.request
from concurrent.futures import ThreadPoolExecutor
from PIL import Image

BASE = 'https://play.pokemonshowdown.com/sprites/'
ids = set(json.loads(re.search(r'=\s*(\{.*\})', open('pokemon.js', encoding='utf8').read()).group(1)).values())

def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': 'shiny-tracker'})) as r:
        return r.read()

def crop(path):
    im = Image.open(io.BytesIO(get(BASE + path))).convert('RGBA')
    assert im.size == (96, 96), (path, im.size)  # the page assumes a 96x96 canvas
    x0, y0, x1, y1 = im.getbbox()
    return [x0, y0, x1 - x0, y1 - y0]

crops = {}
with ThreadPoolExecutor(16) as pool:
    for g in (2, 3, 4):
        listing = get(BASE + 'gen%d-shiny/' % g).decode()
        names = sorted(set(re.findall(r'href="\./([a-z0-9-]+)\.png"', listing)) & ids)
        crops[g] = dict(zip(names, pool.map(lambda n: crop('gen%d-shiny/%s.png' % (g, n)), names)))

with open('sprites.js', 'w', encoding='utf8') as f:
    f.write('// Generated by sprite_crops.py: [x, y, width, height] of the Pokémon in each 96x96 Gen 2-4 shiny sprite\n')
    f.write('var CROPS = ' + json.dumps(crops, separators=(',', ':')) + ';\n')
print({g: len(c) for g, c in crops.items()})
